# Generated by Django 6.1.1 on 2026-09-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('RIDER', 'Rider'), ('ADMIN', 'Admin')], default='BUYER', max_length=10),
        ),
    ]
